# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master

name: deploy-shiny

jobs:
  deploy-shiny:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: install-packages
        run: |
         Rscript -e "install.packages(c('shiny', 'rsconnect', 'remotes'), type = 'binary', dependencies = TRUE)"
         Rscript -e "remotes::install_deps(type = 'binary', force = FALSE, dependencies = TRUE)"
      - name: authorise-shiny
        run: |
         Rscript -e "rsconnect::setAccountInfo(name = 'djpr-spp', token = '${{secrets.SHINYAPPS_TOKEN}}', secret = '${{secrets.SHINYAPPS_SECRET}}')"
         Rscript -e "rsconnect::deployApp(appName = 'djprlabourdash')"
